meta_product_name: "i!iusicz"
meta_title: "i!iusicz | Play music the right way."
meta_description: "Centralize your music in a unique place."
meta_image: "background-4.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
